@Library('Libraries')_
pipeline
{
    agent any
    stages
    {
        stage('continuousdownload')
        {
            steps
            {
                script
                {
                    cicd.mygit("https://github.com/intelliqittrainings/maven.git")
                }
            }
        }
        stage('continuousbuild')
        {
            steps
            {
                script
                {
                    cicd.mybuild()
                }
            }
        }
        stage('continousdeploy')
        {
            steps
            {
                script
                {
                    cicd.mydeploy("declarativepipeline2","172.31.1.203","test2.war")
                }
            }
        }
        stage('continoustesting')
        {
            steps
            {
                script
                {
                    cicd.mygit("https://github.com/intelliqittrainings/FunctionalTesting.git")
                    cicd.mytest()
                }
            }
        }
        stage('continousdelivery')
        {
            steps
            {
                script
                {
                    cicd.mydeploy("declarativepipeline2","172.31.1.21","prod.war")
                }
            }
        }
    }
}
